### PR TITLE
Show remaining hours to level goal

### PR DESCRIPTION
**Pull request by conker-rsc**
Something I found myself calculating manually pretty often, thought it might be nice to just add it in.

Should be rounding up by default and I configured it to show 0-1 fractional digits ie "4" or "4.5".

### CODE REVIEW

**Comment by conker-rsc** [comment]
Just realized this is one of the items listed in: https://github.com/RSCPlus/rscplus/issues/87

Let me know what you think of this implementation, adding another line for minutes should be pretty trivial as well

**Comment by Hubcapp** [comment]
I would do HH:MM format "Time until Level"

**Comment by conker-rsc** [comment]
> I would do HH:MM format "Time until Level"

That seems so obvious in hindsight, haha. Thanks

**Comment by Hubcapp** [comment]
Sorry for the delay. after seeing it in game, I think I want to tweak the format a bit more, but I'll do that post-merge.
Screenshot from 2022-10-13 14 10 18

**Pull request merged**
