### PR TITLE
Initial cancel recovery change

### PR DESCRIPTION
**Pull request by lmsv-mx123**
Last part for #41 , covering the cancel part of set/change recovery questions

### CODE REVIEW

**Comment by Hubcapp** [comment]
This is a good reimplementation, but it's actually super frustrating to have to precisely click "That was me" every time the user logs in for 2 weeks.

In the current master of RSC+, you can close the welcome screen by clicking anywhere (sometimes takes multiple clicks). This is not possible while the "That's ok, activate the new questions" dialogue is up. The button the user now has to click is like 10 pixels tall & if you go up by just a few pixels, you will cancel your recovery questions with no confirm dialogue.

I don't know if this is how it really was in 2003 but we can do better than this interface... 

Honestly, the current interface is really good, just telling the user `Do this from the 'account management' area on our front webpage`.

----

I think this PR probably needs 2 additional toggles.

1) Security tip of the day is cool, but also clutters the welcome box. The tips are really outdated (of course), so, it's Cool, but, I would like to be able to enable/disable it separately from the rest of the features.

2) This cancel recovery questions dialogue should be off by default, and we can instead inject a system message if we detect that it has been less than 2 weeks since account settings were changed. The system message can say
> If you wish to cancel your request, type ::cancelrecoveryrequest, or enable
> the "Cancel Recovery Change" box under the General settings tab.

The ::cancelrecoveryrequest command can send opcode 196.

**Comment by lmsv-mx123** [comment]
For point 1, it is already a toggle. For point 2, working as counter proposal which I think is more suited, a toggle to confirm if the player wishes to do the cancel

**Comment by lmsv-mx123** [comment]
Fixed the issue of the clicking somewhere else did not close the welcome screen. By fix I mean behaves identical to how was before this PR

**Comment by Hubcapp** [comment]
LGTM, tested new features, they work well. If you'd like to center the new "Are you sure you wish to cancel your most recent recovery question request?", that would be fine, but if you can't be bothered, that is fine too.

**Review by Hubcapp — APPROVED** [review]

**Comment by lmsv-mx123** [comment]
Would focus that part of the centering in a future PR since is not exclusive to the added thing but in general the show input popup

**Pull request merged**
