### PR TITLE
Load chat history after relogging

### PR DESCRIPTION
**Pull request by conker-rsc**
Implement an option which preserves the chat history tabs after relogging

### CODE REVIEW

**Comment by Hubcapp** [comment]
I think 2018 Logg was conservative in making this feature off by default. it could be on by default.

**Comment by Hubcapp** [comment]
Tests good otherwise.

**Review by Hubcapp — APPROVED** [review]

**Review by Hubcapp — CHANGES_REQUESTED** [review]
Requesting that default value be set to true

**Comment by conker-rsc** [comment]
Changed default setting

**Pull request merged**
